name: continuous integration

on:
  push:
    branches:
      - test
    paths-ignore:
      - '**/*.md'

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      
      - name: Verify dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  vulnerability-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Verify dependencies
        run: go mod tidy
        
      - name: Run vulnerability check
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24
          go-package: ./...